# DiVerify Configuration File

[settings]
fulcio_url = "http://sigstore-fulcio:5000"
rekor_url = "http://sigstore-rekor:3000"
oauth_issuer_url = "http://sigstore-dex:6000"
diverify_url = "http://localhost:8001"
# tuf_url = "http://localhost:8081"

sigstore_trusted_root = "config/trusted_root.json"

